In [23]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


In [9]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

# Yes ,there is a diffrence between a list and numpy.array.


# Advantages of using numpy array over Lists are:
#     1.numpy array consumes less memory compared to lists.
#     2.Faster compared to lists.
#     3.More Convenient to use.
print(array_list)
print('The Type of variable array_list is ',type(array_list))
print('The Type of a particular variable array_list is ',type(array_list[0]))

print()

print(list_)
print('The Type of variable list_ is ',type(list_))
print('The Type of a particuular variable list_ is ',type(list_[0]))

['1' '2' '3' '4' '5']
The Type of variable array_list is  <class 'numpy.ndarray'>
The Type of a particular variable array_list is  <class 'numpy.str_'>

['1', '2', '3', '4', '5']
The Type of variable list_ is  <class 'list'>
The Type of a particuular variable list_ is  <class 'str'>


In [13]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

for x in list_:
    print('The Type of variable list_ for  element {} is {} '.format(x,type(x)))
    
for x in array_list:
    print('The Type of variable array_list for  element {} is {} '.format(x,type(x)))    

The Type of variable list_ for  element 1 is <class 'str'> 
The Type of variable list_ for  element 2 is <class 'str'> 
The Type of variable list_ for  element 3 is <class 'str'> 
The Type of variable list_ for  element 4 is <class 'str'> 
The Type of variable list_ for  element 5 is <class 'str'> 
The Type of variable array_list for  element 1 is <class 'numpy.str_'> 
The Type of variable array_list for  element 2 is <class 'numpy.str_'> 
The Type of variable array_list for  element 3 is <class 'numpy.str_'> 
The Type of variable array_list for  element 4 is <class 'numpy.str_'> 
The Type of variable array_list for  element 5 is <class 'numpy.str_'> 


In [15]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

array_list = np.array(object = list_, dtype = int)


for x in list_:
    print('The Type of variable list_ for  element {} is {} '.format(x,type(x)))
    
for x in array_list:
    print('The Type of variable array_list for  element {} is {} '.format(x,type(x)))  
    
    
Yes ,the data type for variable array_list has changed to int.In short, all the elements are type casted to int.

The Type of variable list_ for  element 1 is <class 'str'> 
The Type of variable list_ for  element 2 is <class 'str'> 
The Type of variable list_ for  element 3 is <class 'str'> 
The Type of variable list_ for  element 4 is <class 'str'> 
The Type of variable list_ for  element 5 is <class 'str'> 
The Type of variable array_list for  element 1 is <class 'numpy.int64'> 
The Type of variable array_list for  element 2 is <class 'numpy.int64'> 
The Type of variable array_list for  element 3 is <class 'numpy.int64'> 
The Type of variable array_list for  element 4 is <class 'numpy.int64'> 
The Type of variable array_list for  element 5 is <class 'numpy.int64'> 


In [16]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [17]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

print('The Shape of the variable num_array is {}'.format(num_array.shape))
print()
print('The Size of the variable num_array is {}'.format(num_array.size))

The Shape of the variable num_array is (2, 3)

The Size of the variable num_array is 6


In [18]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

new_arr=np.eye(5,5)
print(new_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
